### ISSUE TITLE
Impossible de charger l'extension 'easyimport' 

### ISSUE THREAD

**Issue by ponceta** [VilleDePully/EasyImport#19]
https://raw.githubusercontent.com/VilleDePully/EasyImport/master/plugins.xml

```
Impossible de charger l'extension 'easyimport' 

ModuleNotFoundError: No module named 'easyimport' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'easyimport'


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.3-Madeira Madeira, 2f64a3c4e7 

Chemin Python :
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python
C:/Users/adminap/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/adminap/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/adminap/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/51376332-5fa75180-1b08-11e9-8b97-586844819b5a.png)

![image](https://user-images.githubusercontent.com/8614223/51376357-6afa7d00-1b08-11e9-9cee-2d6660d85dcf.png)

**Comment by ponceta** [comment]
Fixed :

https://github.com/VilleDePully/EasyImport/commit/e49a7114a334d09b4159fe52133dc785ad0bfd05
